/**
 * Universal Channel Protocol (UCP) — Rich Message Types
 *
 * Extends the existing ChannelIncomingMessage/ChannelOutgoingMessage
 * with rich content types, capability negotiation, and cross-channel
 * features (threads, bridging).
 *
 * The UCP layer sits between channel adapters and the MessageBus:
 *   Platform SDK → ChannelPluginAPI → UCPMessage → MessageBus → Agent
 */

import type { ChannelPlatform } from '../types.js';

// ============================================================================
// Content Types
// ============================================================================

/** Rich content types supported by UCP. */
export type UCPContentType =
  | 'text'
  | 'image'
  | 'file'
  | 'audio'
  | 'video'
  | 'location'
  | 'contact'
  | 'reaction'
  | 'sticker'
  | 'card'
  | 'button_group'
  | 'form';

/** Channel features for capability negotiation. */
export type UCPFeature =
  | 'rich_text'
  | 'markdown'
  | 'html'
  | 'images'
  | 'files'
  | 'audio'
  | 'video'
  | 'reactions'
  | 'threads'
  | 'editing'
  | 'deletion'
  | 'typing_indicator'
  | 'read_receipts'
  | 'buttons'
  | 'cards'
  | 'forms'
  | 'voice_messages'
  | 'stickers'
  | 'polls';

// ============================================================================
// Content Blocks
// ============================================================================

/** Interactive button in a UCP message. */
export interface UCPButton {
  id: string;
  label: string;
  action: 'callback' | 'url' | 'command';
  value: string;
}

/** Form field for interactive forms. */
export interface UCPFormField {
  id: string;
  label: string;
  type: 'text' | 'number' | 'select' | 'date' | 'boolean';
  required: boolean;
  options?: string[];
  defaultValue?: unknown;
}

/**
 * A single content block within a UCPMessage.
 *
 * Messages can contain multiple blocks (e.g., text + image + buttons).
 * Not all fields are relevant for every content type.
 */
export interface UCPContent {
  type: UCPContentType;

  // --- Text ---
  text?: string;
  format?: 'plain' | 'markdown' | 'html';

  // --- Media ---
  url?: string;
  data?: Uint8Array;
  mimeType?: string;
  fileName?: string;
  fileSize?: number;
  thumbnailUrl?: string;

  // --- Location ---
  latitude?: number;
  longitude?: number;
  locationName?: string;

  // --- Contact ---
  contactName?: string;
  contactPhone?: string;
  contactEmail?: string;

  // --- Reaction ---
  emoji?: string;
  targetMessageId?: string;

  // --- Interactive ---
  buttons?: UCPButton[];
  fields?: UCPFormField[];

  // --- Card ---
  title?: string;
  description?: string;
  imageUrl?: string;
}

// ============================================================================
// Identity
// ============================================================================

/** Normalized user identity across platforms. */
export interface UCPIdentity {
  /** Platform-specific user ID */
  id: string;
  /** Display name */
  displayName?: string;
  /** Username (e.g., @username) */
  username?: string;
  /** Avatar URL */
  avatarUrl?: string;
  /** Platform this identity belongs to */
  platform: ChannelPlatform;
  /** Whether this is a bot/system user */
  isBot?: boolean;
}

// ============================================================================
// Message
// ============================================================================

/** Metadata attached to a UCPMessage. */
export interface UCPMetadata {
  /** Original platform message object (for advanced platform-specific handling) */
  raw?: unknown;
  /** Linked OwnPilot conversation ID */
  conversationId?: string;
  /** Whether the message was edited */
  isEdited?: boolean;
  /** Whether the message was forwarded */
  isForwarded?: boolean;
  /** Original sender if forwarded */
  forwardedFrom?: UCPIdentity;
  /** Reply chain (message IDs from oldest to newest) */
  replyChain?: string[];
  /** Arbitrary key-value pairs for extensibility */
  [key: string]: unknown;
}

/**
 * Universal Channel Protocol Message.
 *
 * The canonical rich message format that normalizes messages across all
 * channel platforms. Each message contains one or more UCPContent blocks.
 *
 * Conversion flow:
 *   Platform SDK message → adapter.normalize() → UCPMessage
 *   UCPMessage → adaptContent(capabilities) → adapter.denormalize() → Platform SDK
 */
export interface UCPMessage {
  /** Unique message ID (generated by OwnPilot) */
  id: string;
  /** Platform-specific message ID */
  externalId: string;
  /** Channel platform */
  channel: ChannelPlatform;
  /** Channel plugin instance ID (e.g., 'channel.telegram') */
  channelInstanceId: string;
  /** Message direction */
  direction: 'inbound' | 'outbound';
  /** Sender identity */
  sender: UCPIdentity;
  /** Recipient identity (for DMs) */
  recipient?: UCPIdentity;
  /** Content blocks */
  content: UCPContent[];
  /** Unified cross-channel thread ID */
  threadId?: string;
  /** Reply-to message ID */
  replyToId?: string;
  /** Message timestamp */
  timestamp: Date;
  /** Additional metadata */
  metadata: UCPMetadata;
}

// ============================================================================
// Channel Capabilities
// ============================================================================

/** Platform limits for content. */
export interface UCPChannelLimits {
  maxTextLength?: number;
  maxFileSize?: number;
  maxImageSize?: number;
  maxButtons?: number;
  maxCardsPerMessage?: number;
  supportedMediaTypes?: string[];
}

/**
 * Declares what a channel platform supports.
 *
 * Used by the content adaptation layer to auto-degrade rich content
 * for platforms that don't support it (e.g., buttons → text menu on SMS).
 */
export interface UCPChannelCapabilities {
  /** Platform identifier */
  channel: ChannelPlatform;
  /** Feature support map */
  features: Set<UCPFeature>;
  /** Platform-specific limits */
  limits: UCPChannelLimits;
}

// ============================================================================
// Bridge
// ============================================================================

/** Direction for channel bridging. */
export type BridgeDirection = 'source_to_target' | 'target_to_source' | 'both';

/** Configuration for bridging messages between two channel instances. */
export interface UCPBridgeConfig {
  id: string;
  sourceChannelId: string;
  targetChannelId: string;
  direction: BridgeDirection;
  /** Optional regex pattern to filter which messages are bridged */
  filterPattern?: string;
  enabled: boolean;
  createdAt: Date;
}

// ============================================================================
// Content Adaptation
// ============================================================================

/**
 * Adapt a UCPMessage's content to fit the target channel's capabilities.
 *
 * - Buttons → numbered text menu if channel lacks 'buttons'
 * - Markdown → stripped to plain text if channel lacks 'markdown'
 * - Text truncated to channel's maxTextLength
 * - Cards → text blocks if channel lacks 'cards'
 */
export function adaptContent(msg: UCPMessage, capabilities: UCPChannelCapabilities): UCPMessage {
  const adapted: UCPMessage = {
    ...msg,
    content: msg.content.map((c) => adaptBlock(c, capabilities)),
  };
  return adapted;
}

function adaptBlock(content: UCPContent, cap: UCPChannelCapabilities): UCPContent {
  let result = { ...content };

  // Buttons → text menu
  if (result.type === 'button_group' && !cap.features.has('buttons')) {
    result = buttonsToText(result);
  }

  // Cards → text block
  if (result.type === 'card' && !cap.features.has('cards')) {
    result = cardToText(result);
  }

  // Markdown → plain text
  if (result.format === 'markdown' && !cap.features.has('markdown')) {
    result = { ...result, text: stripMarkdown(result.text ?? ''), format: 'plain' };
  }

  // HTML → plain text
  if (result.format === 'html' && !cap.features.has('html')) {
    result = { ...result, text: stripHtml(result.text ?? ''), format: 'plain' };
  }

  // Truncate text
  if (result.type === 'text' && cap.limits.maxTextLength && result.text) {
    const max = cap.limits.maxTextLength;
    if (result.text.length > max) {
      result = { ...result, text: result.text.slice(0, max - 14) + '\n[truncated]' };
    }
  }

  return result;
}

// ============================================================================
// Content Conversion Helpers
// ============================================================================

function buttonsToText(content: UCPContent): UCPContent {
  if (!content.buttons?.length) return { ...content, type: 'text' };
  const lines = content.buttons.map((b, i) => `${i + 1}. ${b.label}`);
  const prefix = content.text ? `${content.text}\n\n` : '';
  return {
    type: 'text',
    text: prefix + lines.join('\n'),
    format: 'plain',
  };
}

function cardToText(content: UCPContent): UCPContent {
  const parts: string[] = [];
  if (content.title) parts.push(`**${content.title}**`);
  if (content.description) parts.push(content.description);
  if (content.url) parts.push(content.url);
  return {
    type: 'text',
    text: parts.join('\n'),
    format: 'plain',
  };
}

/** Strip Markdown formatting to plain text. */
export function stripMarkdown(text: string): string {
  return text
    .replace(/\*\*(.*?)\*\*/g, '$1') // bold
    .replace(/\*(.*?)\*/g, '$1') // italic
    .replace(/~~(.*?)~~/g, '$1') // strikethrough
    .replace(/`{3}[\s\S]*?`{3}/g, (m) => m.replace(/`{3}\w*\n?/g, '').trim()) // code blocks
    .replace(/`(.*?)`/g, '$1') // inline code
    .replace(/#{1,6}\s/g, '') // headings
    .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1') // links
    .replace(/^>\s/gm, '') // blockquotes
    .replace(/^[-*+]\s/gm, '- ') // list items
    .trim();
}

/** Strip HTML tags to plain text. */
export function stripHtml(text: string): string {
  return text
    .replace(/<br\s*\/?>/gi, '\n')
    .replace(/<\/p>/gi, '\n\n')
    .replace(/<[^>]+>/g, '')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .trim();
}
