import React, { useState } from 'react';
import { X, Layout, Zap, Brain, Database, Clock, Settings } from '../icons';

export interface WorkflowTemplate {
  id: string;
  name: string;
  description: string;
  category: string;
  nodeCount: number;
  definition: {
    name: string;
    nodes: unknown[];
    edges: unknown[];
    variables?: Record<string, unknown>;
  };
}

interface TemplateGalleryProps {
  onUseTemplate: (template: WorkflowTemplate) => void;
  onClose: () => void;
}

const TEMPLATES: WorkflowTemplate[] = [
  {
    id: 'daily-summary',
    name: 'Daily Summary',
    description: 'Schedule a daily summary generated by LLM and sent as notification',
    category: 'Scheduling',
    nodeCount: 3,
    definition: {
      name: 'Daily Summary',
      nodes: [
        { id: '1', type: 'trigger', label: 'Schedule Trigger', position: { x: 100, y: 100 }, data: { schedule: '0 9 * * *' } },
        { id: '2', tool: 'llm', label: 'Generate Summary', position: { x: 300, y: 100 }, data: { prompt: 'Generate a daily summary' } },
        { id: '3', type: 'notification', label: 'Send Notification', position: { x: 500, y: 100 }, data: {} },
      ],
      edges: [
        { id: 'e1-2', source: '1', target: '2' },
        { id: 'e2-3', source: '2', target: '3' },
      ],
      variables: { summaryPrompt: 'Summarize the following data' },
    },
  },
  {
    id: 'webhook-handler',
    name: 'Webhook Handler',
    description: 'Receive webhook, transform data, and forward to external API',
    category: 'Integration',
    nodeCount: 3,
    definition: {
      name: 'Webhook Handler',
      nodes: [
        { id: '1', type: 'webhook', label: 'Webhook Trigger', position: { x: 100, y: 100 }, data: { path: '/webhook' } },
        { id: '2', type: 'transformer', label: 'Transform Data', position: { x: 300, y: 100 }, data: { mapping: {} } },
        { id: '3', type: 'http', label: 'HTTP POST', position: { x: 500, y: 100 }, data: { method: 'POST', url: '' } },
      ],
      edges: [
        { id: 'e1-2', source: '1', target: '2' },
        { id: 'e2-3', source: '2', target: '3' },
      ],
    },
  },
  {
    id: 'data-backup',
    name: 'Data Backup',
    description: 'Scheduled data export and upload to remote storage',
    category: 'Data',
    nodeCount: 3,
    definition: {
      name: 'Data Backup',
      nodes: [
        { id: '1', type: 'trigger', label: 'Schedule Trigger', position: { x: 100, y: 100 }, data: { schedule: '0 2 * * *' } },
        { id: '2', type: 'code', label: 'Export Data', position: { x: 300, y: 100 }, data: { code: 'return data;' } },
        { id: '3', type: 'http', label: 'Upload', position: { x: 500, y: 100 }, data: { method: 'POST', url: '' } },
      ],
      edges: [
        { id: 'e1-2', source: '1', target: '2' },
        { id: 'e2-3', source: '2', target: '3' },
      ],
    },
  },
  {
    id: 'content-generator',
    name: 'Content Generator',
    description: 'Generate content with LLM and send notification when ready',
    category: 'AI',
    nodeCount: 3,
    definition: {
      name: 'Content Generator',
      nodes: [
        { id: '1', type: 'trigger', label: 'Manual Trigger', position: { x: 100, y: 100 }, data: {} },
        { id: '2', tool: 'llm', label: 'Generate Content', position: { x: 300, y: 100 }, data: { prompt: 'Generate content' } },
        { id: '3', type: 'notification', label: 'Notify', position: { x: 500, y: 100 }, data: {} },
      ],
      edges: [
        { id: 'e1-2', source: '1', target: '2' },
        { id: 'e2-3', source: '2', target: '3' },
      ],
      variables: { contentType: 'blog post', topic: '' },
    },
  },
  {
    id: 'email-digest',
    name: 'Email Digest',
    description: 'Fetch data, format with LLM, and send as email digest',
    category: 'Scheduling',
    nodeCount: 4,
    definition: {
      name: 'Email Digest',
      nodes: [
        { id: '1', type: 'trigger', label: 'Schedule Trigger', position: { x: 100, y: 100 }, data: { schedule: '0 8 * * 1' } },
        { id: '2', type: 'http', label: 'Fetch Data', position: { x: 250, y: 100 }, data: { method: 'GET', url: '' } },
        { id: '3', tool: 'llm', label: 'Format Digest', position: { x: 400, y: 100 }, data: { prompt: 'Format as digest' } },
        { id: '4', type: 'notification', label: 'Send Email', position: { x: 550, y: 100 }, data: {} },
      ],
      edges: [
        { id: 'e1-2', source: '1', target: '2' },
        { id: 'e2-3', source: '2', target: '3' },
        { id: 'e3-4', source: '3', target: '4' },
      ],
    },
  },
  {
    id: 'approval-flow',
    name: 'Approval Flow',
    description: 'Analyze request with LLM and route through approval gate',
    category: 'Automation',
    nodeCount: 3,
    definition: {
      name: 'Approval Flow',
      nodes: [
        { id: '1', type: 'trigger', label: 'Manual Trigger', position: { x: 100, y: 100 }, data: {} },
        { id: '2', tool: 'llm', label: 'Analyze Request', position: { x: 300, y: 100 }, data: { prompt: 'Analyze this request' } },
        { id: '3', type: 'approval', label: 'Approval Gate', position: { x: 500, y: 100 }, data: {} },
      ],
      edges: [
        { id: 'e1-2', source: '1', target: '2' },
        { id: 'e2-3', source: '2', target: '3' },
      ],
    },
  },
  {
    id: 'multi-step-agent',
    name: 'Multi-Step Agent',
    description: 'LLM decision routing to different tool branches based on condition',
    category: 'AI',
    nodeCount: 5,
    definition: {
      name: 'Multi-Step Agent',
      nodes: [
        { id: '1', type: 'trigger', label: 'Manual Trigger', position: { x: 100, y: 150 }, data: {} },
        { id: '2', tool: 'llm', label: 'Decide Action', position: { x: 250, y: 150 }, data: { prompt: 'Decide next action' } },
        { id: '3', type: 'condition', label: 'Route', position: { x: 400, y: 150 }, data: { condition: '' } },
        { id: '4', tool: 'search', label: 'Search Tool', position: { x: 550, y: 80 }, data: {} },
        { id: '5', tool: 'code', label: 'Code Tool', position: { x: 550, y: 220 }, data: {} },
      ],
      edges: [
        { id: 'e1-2', source: '1', target: '2' },
        { id: 'e2-3', source: '2', target: '3' },
        { id: 'e3-4', source: '3', target: '4', sourceHandle: 'true' },
        { id: 'e3-5', source: '3', target: '5', sourceHandle: 'false' },
      ],
    },
  },
  {
    id: 'data-pipeline',
    name: 'Data Pipeline',
    description: 'Fetch data, transform with code, and process each item',
    category: 'Data',
    nodeCount: 4,
    definition: {
      name: 'Data Pipeline',
      nodes: [
        { id: '1', type: 'trigger', label: 'Manual Trigger', position: { x: 100, y: 100 }, data: {} },
        { id: '2', type: 'http', label: 'Fetch Data', position: { x: 250, y: 100 }, data: { method: 'GET', url: '' } },
        { id: '3', type: 'code', label: 'Transform', position: { x: 400, y: 100 }, data: { code: 'return data.map(x => x);' } },
        { id: '4', type: 'foreach', label: 'Process Each', position: { x: 550, y: 100 }, data: {} },
      ],
      edges: [
        { id: 'e1-2', source: '1', target: '2' },
        { id: 'e2-3', source: '2', target: '3' },
        { id: 'e3-4', source: '3', target: '4' },
      ],
    },
  },
  {
    id: 'error-monitored',
    name: 'Error Monitored',
    description: 'Execute code with error handling and notification on failure',
    category: 'Automation',
    nodeCount: 4,
    definition: {
      name: 'Error Monitored',
      nodes: [
        { id: '1', type: 'trigger', label: 'Manual Trigger', position: { x: 100, y: 100 }, data: {} },
        { id: '2', type: 'code', label: 'Execute', position: { x: 250, y: 100 }, data: { code: 'return result;' } },
        { id: '3', type: 'error', label: 'Error Handler', position: { x: 250, y: 200 }, data: {} },
        { id: '4', type: 'notification', label: 'Alert', position: { x: 400, y: 200 }, data: {} },
      ],
      edges: [
        { id: 'e1-2', source: '1', target: '2' },
        { id: 'e2-3', source: '2', target: '3', sourceHandle: 'error' },
        { id: 'e3-4', source: '3', target: '4' },
      ],
    },
  },
  {
    id: 'parallel-research',
    name: 'Parallel Research',
    description: 'Run multiple LLM queries in parallel, merge results, and transform',
    category: 'AI',
    nodeCount: 5,
    definition: {
      name: 'Parallel Research',
      nodes: [
        { id: '1', type: 'trigger', label: 'Manual Trigger', position: { x: 100, y: 150 }, data: {} },
        { id: '2', tool: 'llm', label: 'Research A', position: { x: 250, y: 50 }, data: { prompt: 'Research topic A' } },
        { id: '3', tool: 'llm', label: 'Research B', position: { x: 250, y: 150 }, data: { prompt: 'Research topic B' } },
        { id: '4', tool: 'llm', label: 'Research C', position: { x: 250, y: 250 }, data: { prompt: 'Research topic C' } },
        { id: '5', type: 'merge', label: 'Merge Results', position: { x: 400, y: 150 }, data: {} },
      ],
      edges: [
        { id: 'e1-2', source: '1', target: '2' },
        { id: 'e1-3', source: '1', target: '3' },
        { id: 'e1-4', source: '1', target: '4' },
        { id: 'e2-5', source: '2', target: '5' },
        { id: 'e3-5', source: '3', target: '5' },
        { id: 'e4-5', source: '4', target: '5' },
      ],
    },
  },
];

const CATEGORIES = ['All', 'AI', 'Scheduling', 'Integration', 'Data', 'Automation'];

const categoryIcons: Record<string, React.ReactElement> = {
  AI: <Brain className="w-3 h-3" />,
  Scheduling: <Clock className="w-3 h-3" />,
  Integration: <Zap className="w-3 h-3" />,
  Data: <Database className="w-3 h-3" />,
  Automation: <Settings className="w-3 h-3" />,
};

export function TemplateGallery({ onUseTemplate, onClose }: TemplateGalleryProps) {
  const [selectedCategory, setSelectedCategory] = useState('All');

  const filteredTemplates =
    selectedCategory === 'All'
      ? TEMPLATES
      : TEMPLATES.filter((t) => t.category === selectedCategory);

  return (
    <div
      className="fixed inset-0 z-50 bg-black/40 flex items-center justify-center"
      onClick={onClose}
    >
      <div
        className="bg-bg-secondary dark:bg-dark-bg-secondary rounded-xl shadow-2xl border border-border dark:border-dark-border max-w-3xl w-full max-h-[80vh] flex flex-col"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-border dark:border-dark-border">
          <div className="flex items-center gap-2">
            <Layout className="w-5 h-5 text-primary" />
            <h2 className="text-lg font-semibold text-text-primary dark:text-dark-text-primary">
              Workflow Templates
            </h2>
          </div>
          <button
            onClick={onClose}
            className="p-1 hover:bg-bg-primary dark:hover:bg-dark-bg-primary rounded transition-colors"
            aria-label="Close"
          >
            <X className="w-5 h-5 text-text-muted dark:text-dark-text-muted" />
          </button>
        </div>

        {/* Category Tabs */}
        <div className="flex gap-2 px-6 py-3 border-b border-border dark:border-dark-border overflow-x-auto">
          {CATEGORIES.map((category) => (
            <button
              key={category}
              onClick={() => setSelectedCategory(category)}
              className={`px-3 py-1.5 text-sm font-medium rounded-lg transition-colors whitespace-nowrap ${
                selectedCategory === category
                  ? 'bg-primary text-white'
                  : 'bg-bg-primary dark:bg-dark-bg-primary text-text-muted dark:text-dark-text-muted hover:text-text-primary dark:hover:text-dark-text-primary'
              }`}
            >
              {category}
            </button>
          ))}
        </div>

        {/* Template Grid */}
        <div className="flex-1 overflow-y-auto p-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {filteredTemplates.map((template) => (
              <div
                key={template.id}
                className="border border-border dark:border-dark-border rounded-lg p-4 hover:border-primary/50 transition-colors cursor-pointer"
                onClick={() => onUseTemplate(template)}
              >
                <div className="flex items-start justify-between mb-2">
                  <h3 className="font-semibold text-text-primary dark:text-dark-text-primary">
                    {template.name}
                  </h3>
                  <div className="flex items-center gap-1 px-2 py-0.5 text-[10px] font-medium rounded-full bg-primary/10 text-primary">
                    {categoryIcons[template.category]}
                    <span>{template.category}</span>
                  </div>
                </div>
                <p className="text-sm text-text-muted dark:text-dark-text-muted mb-3">
                  {template.description}
                </p>
                <div className="flex items-center justify-between">
                  <span className="text-xs text-text-muted dark:text-dark-text-muted">
                    {template.nodeCount} nodes
                  </span>
                  <button
                    onClick={(e) => {
                      e.stopPropagation();
                      onUseTemplate(template);
                    }}
                    className="px-3 py-1 text-xs font-medium bg-primary text-white rounded hover:bg-primary/90 transition-colors"
                  >
                    Use Template
                  </button>
                </div>
              </div>
            ))}
          </div>

          {filteredTemplates.length === 0 && (
            <div className="text-center py-12 text-text-muted dark:text-dark-text-muted">
              No templates found in this category
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
