import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    globals: true,
    environment: 'node',
    include: ['src/**/*.test.ts', 'test/**/*.test.ts'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'lcov', 'html'],
      include: ['src/**/*.ts'],
      exclude: [
        'src/**/*.test.ts',
        'src/**/index.ts',
        'src/**/types.ts',
        'src/**/*-types.ts',
        'src/**/test-helpers.ts',
        'src/services/audit-service.ts',
        'src/services/config-center.ts',
        'src/services/database-service.ts',
        'src/services/embedding-service.ts',
        'src/services/extension-service.ts',
        'src/services/goal-service.ts',
        'src/services/heartbeat-service.ts',
        'src/services/log-service.ts',
        'src/services/management-service.ts',
        'src/services/mcp-client-interface.ts',
        'src/services/message-bus.ts',
        'src/services/message-types.ts',
        'src/services/plan-service.ts',
        'src/services/plugin-service.ts',
        'src/services/provider-service.ts',
        'src/services/pulse-service.ts',
        'src/services/resource-service.ts',
        'src/services/session-service.ts',
        'src/services/tool-service.ts',
        'src/services/trigger-service.ts',
        'src/services/workflow-service.ts',
        'src/services/workspace-service.ts',
        'src/events/event-map.ts',
        'src/events/hook-map.ts',
        'src/channels/events.ts',
      ],
      thresholds: {
        statements: 80,
        branches: 80,
        functions: 80,
        lines: 80,
      },
    },
    typecheck: {
      enabled: true,
    },
  },
});
