/**
 * AI workflow templates.
 *
 * Split by category out of workflow-templates.ts (1268 LOC). Data only —
 * the catalog is re-exported unchanged from that file.
 */

import type { WorkflowTemplate } from '../workflow-templates';

export const AI_TEMPLATES: WorkflowTemplate[] = [
  {
    id: 'smart-content-pipeline',
    name: 'Smart Content Pipeline',
    description: 'Generate content with AI, auto-review for quality, revise if needed',
    category: 'AI',
    nodeCount: 6,
    definition: {
      name: 'Smart Content Pipeline',
      nodes: [
        {
          id: 'node_1',
          type: 'trigger',
          triggerType: 'manual',
          label: 'Start',
          position: { x: 100, y: 150 },
        },
        {
          id: 'node_2',
          type: 'llm',
          label: 'Generate Draft',
          provider: 'default',
          model: 'default',
          systemPrompt:
            "You are an expert content writer. Write high-quality, engaging content based on the user's request.",
          userMessage:
            'Write a {{variables.contentType}} about: {{variables.topic}}\n\nTone: {{variables.tone}}\nTarget audience: {{variables.audience}}',
          temperature: 0.8,
          maxTokens: 4096,
          position: { x: 350, y: 150 },
        },
        {
          id: 'node_3',
          type: 'llm',
          label: 'Quality Review',
          provider: 'default',
          model: 'default',
          systemPrompt:
            'You are a strict content reviewer. Rate the content on a scale of 1-10 for quality, clarity, and engagement. If the score is 7 or above, respond with "PASS: [score]". If below 7, respond with "REVISE: [specific improvements needed]".',
          userMessage: 'Review this {{variables.contentType}}:\n\n{{node_2.output}}',
          temperature: 0.3,
          maxTokens: 1024,
          position: { x: 600, y: 150 },
        },
        {
          id: 'node_4',
          type: 'condition',
          label: 'Quality Check',
          expression: 'typeof data === "string" && data.startsWith("PASS")',
          position: { x: 850, y: 150 },
        },
        {
          id: 'node_5',
          type: 'notification',
          label: 'Content Ready',
          message: 'Your {{variables.contentType}} is ready:\n\n{{node_2.output}}',
          severity: 'success',
          position: { x: 1100, y: 50 },
        },
        {
          id: 'node_6',
          type: 'llm',
          label: 'Revise Content',
          provider: 'default',
          model: 'default',
          systemPrompt:
            "You are an expert editor. Revise the content based on the reviewer's feedback while preserving the original intent and voice.",
          userMessage:
            'Original content:\n{{node_2.output}}\n\nReviewer feedback:\n{{node_3.output}}\n\nPlease revise accordingly.',
          temperature: 0.6,
          maxTokens: 4096,
          position: { x: 1100, y: 250 },
        },
      ],
      edges: [
        { source: 'node_1', target: 'node_2' },
        { source: 'node_2', target: 'node_3' },
        { source: 'node_3', target: 'node_4' },
        { source: 'node_4', target: 'node_5', sourceHandle: 'true' },
        { source: 'node_4', target: 'node_6', sourceHandle: 'false' },
      ],
      variables: {
        contentType: 'blog post',
        topic: 'AI automation in daily life',
        tone: 'professional but approachable',
        audience: 'tech-savvy professionals',
      },
    },
  },
  {
    id: 'multi-intent-router',
    name: 'Multi-Intent Router',
    description: 'Classify user input into categories and route to specialized AI handlers',
    category: 'AI',
    nodeCount: 7,
    definition: {
      name: 'Multi-Intent Router',
      nodes: [
        {
          id: 'node_1',
          type: 'trigger',
          triggerType: 'manual',
          label: 'User Input',
          position: { x: 100, y: 200 },
        },
        {
          id: 'node_2',
          type: 'llm',
          label: 'Classify Intent',
          provider: 'default',
          model: 'default',
          systemPrompt:
            'Classify the user input into exactly one category. Reply with ONLY the category name, nothing else.\n\nCategories:\n- question (factual questions, how-to)\n- task (action items, things to do)\n- creative (writing, brainstorming, ideas)\n- analysis (data interpretation, research)',
          userMessage: '{{node_1.output}}',
          temperature: 0.1,
          maxTokens: 50,
          position: { x: 350, y: 200 },
        },
        {
          id: 'node_3',
          type: 'switch',
          label: 'Route Intent',
          expression: 'typeof data === "string" ? data.trim().toLowerCase() : "question"',
          cases: [
            { label: 'question', value: 'question' },
            { label: 'task', value: 'task' },
            { label: 'creative', value: 'creative' },
            { label: 'analysis', value: 'analysis' },
          ],
          position: { x: 600, y: 200 },
        },
        {
          id: 'node_4',
          type: 'llm',
          label: 'Answer Question',
          provider: 'default',
          model: 'default',
          systemPrompt:
            'You are a knowledgeable assistant. Provide clear, accurate answers with sources when possible.',
          userMessage: '{{node_1.output}}',
          temperature: 0.4,
          maxTokens: 2048,
          position: { x: 900, y: 30 },
        },
        {
          id: 'node_5',
          type: 'llm',
          label: 'Plan Task',
          provider: 'default',
          model: 'default',
          systemPrompt:
            'You are a task planner. Break down the request into clear, actionable steps with priorities and estimated effort.',
          userMessage: 'Create an action plan for: {{node_1.output}}',
          temperature: 0.5,
          maxTokens: 2048,
          position: { x: 900, y: 150 },
        },
        {
          id: 'node_6',
          type: 'llm',
          label: 'Creative Work',
          provider: 'default',
          model: 'default',
          systemPrompt:
            'You are a creative writing assistant. Be imaginative, original, and engaging.',
          userMessage: '{{node_1.output}}',
          temperature: 0.9,
          maxTokens: 4096,
          position: { x: 900, y: 270 },
        },
        {
          id: 'node_7',
          type: 'llm',
          label: 'Deep Analysis',
          provider: 'default',
          model: 'default',
          systemPrompt:
            'You are a research analyst. Provide thorough, structured analysis with pros/cons, key findings, and recommendations.',
          userMessage: 'Analyze: {{node_1.output}}',
          temperature: 0.4,
          maxTokens: 4096,
          position: { x: 900, y: 390 },
        },
      ],
      edges: [
        { source: 'node_1', target: 'node_2' },
        { source: 'node_2', target: 'node_3' },
        { source: 'node_3', target: 'node_4', sourceHandle: 'question' },
        { source: 'node_3', target: 'node_5', sourceHandle: 'task' },
        { source: 'node_3', target: 'node_6', sourceHandle: 'creative' },
        { source: 'node_3', target: 'node_7', sourceHandle: 'analysis' },
      ],
    },
  },
  {
    id: 'knowledge-capture',
    name: 'Knowledge Capture',
    description: 'Process input with AI, extract key facts, and save as structured memories',
    category: 'AI',
    nodeCount: 5,
    definition: {
      name: 'Knowledge Capture',
      nodes: [
        {
          id: 'node_1',
          type: 'trigger',
          triggerType: 'manual',
          label: 'Input Knowledge',
          position: { x: 100, y: 150 },
        },
        {
          id: 'node_2',
          type: 'llm',
          label: 'Extract Key Facts',
          provider: 'default',
          model: 'default',
          systemPrompt:
            'Extract key facts, insights, and actionable items from the input. Return a JSON array of objects, each with: {"fact": "...", "importance": 1-10, "category": "insight|action|reference"}. Return ONLY valid JSON, no explanation.',
          userMessage: '{{node_1.output}}',
          temperature: 0.3,
          maxTokens: 2048,
          position: { x: 350, y: 150 },
        },
        {
          id: 'node_3',
          type: 'code',
          label: 'Parse Facts',
          language: 'javascript',
          code: 'const text = typeof data === "string" ? data : JSON.stringify(data);\nconst jsonMatch = text.match(/\\[\\s*\\{[\\s\\S]*\\}\\s*\\]/);\nif (!jsonMatch) return [];\ntry { return JSON.parse(jsonMatch[0]); } catch { return []; }',
          position: { x: 600, y: 150 },
        },
        {
          id: 'node_4',
          type: 'forEach',
          label: 'Save Each Fact',
          arrayExpression: '{{node_3.output}}',
          itemVariable: 'fact',
          onError: 'continue',
          position: { x: 850, y: 150 },
        },
        {
          id: 'node_5',
          tool: 'core.create_memory',
          label: 'Store Memory',
          args: { content: '{{fact.fact}}', importance: '{{fact.importance}}' },
          position: { x: 850, y: 300 },
        },
      ],
      edges: [
        { source: 'node_1', target: 'node_2' },
        { source: 'node_2', target: 'node_3' },
        { source: 'node_3', target: 'node_4' },
        { source: 'node_4', target: 'node_5', sourceHandle: 'each' },
      ],
    },
  },
  {
    id: 'parallel-research',
    name: 'Parallel Research',
    description: 'Run 3 specialized AI analyses in parallel, merge results, synthesize a report',
    category: 'AI',
    nodeCount: 8,
    definition: {
      name: 'Parallel Research',
      nodes: [
        {
          id: 'node_1',
          type: 'trigger',
          triggerType: 'manual',
          label: 'Research Topic',
          position: { x: 100, y: 200 },
        },
        {
          id: 'node_2',
          type: 'parallel',
          label: 'Research Branches',
          branchCount: 3,
          branchLabels: ['Technical', 'Market', 'Risks'],
          position: { x: 300, y: 200 },
        },
        {
          id: 'node_3',
          type: 'llm',
          label: 'Technical Analysis',
          provider: 'default',
          model: 'default',
          systemPrompt:
            'You are a technical analyst. Provide deep technical analysis including architecture, implementation challenges, and technology stack recommendations.',
          userMessage: 'Technical analysis of: {{variables.topic}}',
          temperature: 0.5,
          maxTokens: 3000,
          position: { x: 550, y: 50 },
        },
        {
          id: 'node_4',
          type: 'llm',
          label: 'Market Analysis',
          provider: 'default',
          model: 'default',
          systemPrompt:
            'You are a market analyst. Analyze market size, competition, trends, target audience, and go-to-market strategy.',
          userMessage: 'Market analysis of: {{variables.topic}}',
          temperature: 0.5,
          maxTokens: 3000,
          position: { x: 550, y: 200 },
        },
        {
          id: 'node_5',
          type: 'llm',
          label: 'Risk Assessment',
          provider: 'default',
          model: 'default',
          systemPrompt:
            'You are a risk analyst. Identify potential risks, regulatory concerns, scalability issues, and mitigation strategies.',
          userMessage: 'Risk assessment for: {{variables.topic}}',
          temperature: 0.4,
          maxTokens: 2000,
          position: { x: 550, y: 350 },
        },
        {
          id: 'node_6',
          type: 'merge',
          label: 'Combine Results',
          mode: 'waitAll',
          position: { x: 800, y: 200 },
        },
        {
          id: 'node_7',
          type: 'llm',
          label: 'Synthesize Report',
          provider: 'default',
          model: 'default',
          systemPrompt:
            'You are an executive analyst. Synthesize the three research reports into a cohesive executive summary with key findings, recommendations, and next steps. Use clear headings and bullet points.',
          userMessage:
            'Synthesize these three research reports into one executive summary:\n\nTechnical Analysis:\n{{node_3.output}}\n\nMarket Analysis:\n{{node_4.output}}\n\nRisk Assessment:\n{{node_5.output}}',
          temperature: 0.5,
          maxTokens: 4096,
          position: { x: 1050, y: 200 },
        },
        {
          id: 'node_8',
          type: 'notification',
          label: 'Report Ready',
          message: 'Research report for "{{variables.topic}}" is complete.',
          severity: 'success',
          position: { x: 1300, y: 200 },
        },
      ],
      edges: [
        { source: 'node_1', target: 'node_2' },
        { source: 'node_2', target: 'node_3', sourceHandle: 'branch-0' },
        { source: 'node_2', target: 'node_4', sourceHandle: 'branch-1' },
        { source: 'node_2', target: 'node_5', sourceHandle: 'branch-2' },
        { source: 'node_3', target: 'node_6' },
        { source: 'node_4', target: 'node_6' },
        { source: 'node_5', target: 'node_6' },
        { source: 'node_6', target: 'node_7' },
        { source: 'node_7', target: 'node_8' },
      ],
      variables: { topic: 'AI-powered personal assistant platforms' },
    },
  },
  {
    id: 'multi-source-merge',
    name: 'Multi-Source Merge',
    description:
      'Fetch data from 3 APIs in parallel, merge results, transform and synthesize with AI',
    category: 'AI',
    nodeCount: 9,
    definition: {
      name: 'Multi-Source Merge',
      nodes: [
        {
          id: 'node_1',
          type: 'trigger',
          triggerType: 'manual',
          label: 'Start',
          position: { x: 100, y: 200 },
        },
        {
          id: 'node_2',
          type: 'parallel',
          label: 'Fetch Sources',
          branchCount: 3,
          branchLabels: ['Source A', 'Source B', 'Source C'],
          position: { x: 300, y: 200 },
        },
        {
          id: 'node_3',
          type: 'httpRequest',
          label: 'Fetch Source A',
          method: 'GET',
          url: '{{variables.sourceAUrl}}',
          position: { x: 550, y: 50 },
        },
        {
          id: 'node_4',
          type: 'httpRequest',
          label: 'Fetch Source B',
          method: 'GET',
          url: '{{variables.sourceBUrl}}',
          position: { x: 550, y: 200 },
        },
        {
          id: 'node_5',
          type: 'httpRequest',
          label: 'Fetch Source C',
          method: 'GET',
          url: '{{variables.sourceCUrl}}',
          position: { x: 550, y: 350 },
        },
        {
          id: 'node_6',
          type: 'merge',
          label: 'Merge All',
          mode: 'waitAll',
          position: { x: 800, y: 200 },
        },
        {
          id: 'node_7',
          type: 'transformer',
          label: 'Normalize Data',
          expression:
            '({ sourceA: (node_3 && node_3.body) || node_3, sourceB: (node_4 && node_4.body) || node_4, sourceC: (node_5 && node_5.body) || node_5 })',
          position: { x: 1000, y: 200 },
        },
        {
          id: 'node_8',
          type: 'llm',
          label: 'Synthesize Report',
          provider: 'default',
          model: 'default',
          systemPrompt:
            'You are a data synthesis expert. Combine data from multiple sources into a unified analysis. Identify commonalities, discrepancies, and key insights across all sources. Structure your response with clear sections.',
          userMessage:
            'Synthesize data from three sources into a unified report:\n\nSource A:\n{{node_3.output}}\n\nSource B:\n{{node_4.output}}\n\nSource C:\n{{node_5.output}}',
          temperature: 0.5,
          maxTokens: 4096,
          position: { x: 1200, y: 200 },
        },
        {
          id: 'node_9',
          type: 'notification',
          label: 'Synthesis Complete',
          message: 'Multi-source synthesis report is ready.',
          severity: 'success',
          position: { x: 1450, y: 200 },
        },
      ],
      edges: [
        { source: 'node_1', target: 'node_2' },
        { source: 'node_2', target: 'node_3', sourceHandle: 'branch-0' },
        { source: 'node_2', target: 'node_4', sourceHandle: 'branch-1' },
        { source: 'node_2', target: 'node_5', sourceHandle: 'branch-2' },
        { source: 'node_3', target: 'node_6' },
        { source: 'node_4', target: 'node_6' },
        { source: 'node_5', target: 'node_6' },
        { source: 'node_6', target: 'node_7' },
        { source: 'node_7', target: 'node_8' },
        { source: 'node_8', target: 'node_9' },
      ],
      variables: {
        sourceAUrl: 'https://api.example.com/source-a',
        sourceBUrl: 'https://api.example.com/source-b',
        sourceCUrl: 'https://api.example.com/source-c',
      },
    },
  },
];
